apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: shikanime
build:
  artifacts:
    - image: rg.fr-par.scw.cloud/namespace-distracted-kepler/myawesomelist
      ko:
        dir: cmd/myawesomelist
    - image: rg.fr-par.scw.cloud/namespace-distracted-kepler/myawesomelist-www
      context: www
  platforms:
    - linux/amd64
