// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: myawesomelist/v1/myawesomelist.proto

package myawesomelistv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project represents a single project from an awesome list
type Project struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url         string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Presence-aware optional fields (supported in modern proto3)
	StargazersCount *int64 `protobuf:"varint,4,opt,name=stargazers_count,json=stargazersCount,proto3,oneof" json:"stargazers_count,omitempty"`
	OpenIssueCount  *int64 `protobuf:"varint,5,opt,name=open_issue_count,json=openIssueCount,proto3,oneof" json:"open_issue_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Project) GetStargazersCount() int64 {
	if x != nil && x.StargazersCount != nil {
		return *x.StargazersCount
	}
	return 0
}

func (x *Project) GetOpenIssueCount() int64 {
	if x != nil && x.OpenIssueCount != nil {
		return *x.OpenIssueCount
	}
	return 0
}

// Category groups projects under a section
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Projects      []*Project             `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

// Collection represents an awesome repository parsed into categories
type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Categories    []*Category            `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{2}
}

func (x *Collection) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Collection) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

// Identify a source awesome repository (owner/repo)
type RepoRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoRef) Reset() {
	*x = RepoRef{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoRef) ProtoMessage() {}

func (x *RepoRef) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoRef.ProtoReflect.Descriptor instead.
func (*RepoRef) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{3}
}

func (x *RepoRef) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RepoRef) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type ListCollectionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When true, backend enriches projects with GitHub repo info
	IncludeRepoInfo bool `protobuf:"varint,1,opt,name=include_repo_info,json=includeRepoInfo,proto3" json:"include_repo_info,omitempty"`
	// If empty, server uses its DefaultGitHubRepos; otherwise overrides
	Repos         []*RepoRef `protobuf:"bytes,2,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{4}
}

func (x *ListCollectionsRequest) GetIncludeRepoInfo() bool {
	if x != nil {
		return x.IncludeRepoInfo
	}
	return false
}

func (x *ListCollectionsRequest) GetRepos() []*RepoRef {
	if x != nil {
		return x.Repos
	}
	return nil
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*Collection          `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{5}
}

func (x *ListCollectionsResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

type GetCollectionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Repo            *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	IncludeRepoInfo bool                   `protobuf:"varint,2,opt,name=include_repo_info,json=includeRepoInfo,proto3" json:"include_repo_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{6}
}

func (x *GetCollectionRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *GetCollectionRequest) GetIncludeRepoInfo() bool {
	if x != nil {
		return x.IncludeRepoInfo
	}
	return false
}

type GetCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{7}
}

func (x *GetCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type ListCategoriesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Repo            *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	IncludeRepoInfo bool                   `protobuf:"varint,2,opt,name=include_repo_info,json=includeRepoInfo,proto3" json:"include_repo_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{8}
}

func (x *ListCategoriesRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *ListCategoriesRequest) GetIncludeRepoInfo() bool {
	if x != nil {
		return x.IncludeRepoInfo
	}
	return false
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{9}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListProjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Repo  *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	// Exact category name as parsed from README
	CategoryName    string `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	IncludeRepoInfo bool   `protobuf:"varint,3,opt,name=include_repo_info,json=includeRepoInfo,proto3" json:"include_repo_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{10}
}

func (x *ListProjectsRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *ListProjectsRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ListProjectsRequest) GetIncludeRepoInfo() bool {
	if x != nil {
		return x.IncludeRepoInfo
	}
	return false
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{11}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type SearchProjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Optional filter: restrict search to specific repos
	Repos           []*RepoRef `protobuf:"bytes,3,rep,name=repos,proto3" json:"repos,omitempty"`
	IncludeRepoInfo bool       `protobuf:"varint,4,opt,name=include_repo_info,json=includeRepoInfo,proto3" json:"include_repo_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchProjectsRequest) Reset() {
	*x = SearchProjectsRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProjectsRequest) ProtoMessage() {}

func (x *SearchProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProjectsRequest.ProtoReflect.Descriptor instead.
func (*SearchProjectsRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{12}
}

func (x *SearchProjectsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchProjectsRequest) GetRepos() []*RepoRef {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *SearchProjectsRequest) GetIncludeRepoInfo() bool {
	if x != nil {
		return x.IncludeRepoInfo
	}
	return false
}

type SearchProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProjectsResponse) Reset() {
	*x = SearchProjectsResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProjectsResponse) ProtoMessage() {}

func (x *SearchProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProjectsResponse.ProtoReflect.Descriptor instead.
func (*SearchProjectsResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{13}
}

func (x *SearchProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{14}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_myawesomelist_v1_myawesomelist_proto protoreflect.FileDescriptor

const file_myawesomelist_v1_myawesomelist_proto_rawDesc = "" +
	"\n" +
	"$myawesomelist/v1/myawesomelist.proto\x12\x10myawesomelist.v1\"\xda\x01\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12.\n" +
	"\x10stargazers_count\x18\x04 \x01(\x03H\x00R\x0fstargazersCount\x88\x01\x01\x12-\n" +
	"\x10open_issue_count\x18\x05 \x01(\x03H\x01R\x0eopenIssueCount\x88\x01\x01B\x13\n" +
	"\x11_stargazers_countB\x13\n" +
	"\x11_open_issue_count\"U\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\bprojects\x18\x02 \x03(\v2\x19.myawesomelist.v1.ProjectR\bprojects\"d\n" +
	"\n" +
	"Collection\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12:\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x1a.myawesomelist.v1.CategoryR\n" +
	"categories\"3\n" +
	"\aRepoRef\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"u\n" +
	"\x16ListCollectionsRequest\x12*\n" +
	"\x11include_repo_info\x18\x01 \x01(\bR\x0fincludeRepoInfo\x12/\n" +
	"\x05repos\x18\x02 \x03(\v2\x19.myawesomelist.v1.RepoRefR\x05repos\"Y\n" +
	"\x17ListCollectionsResponse\x12>\n" +
	"\vcollections\x18\x01 \x03(\v2\x1c.myawesomelist.v1.CollectionR\vcollections\"q\n" +
	"\x14GetCollectionRequest\x12-\n" +
	"\x04repo\x18\x01 \x01(\v2\x19.myawesomelist.v1.RepoRefR\x04repo\x12*\n" +
	"\x11include_repo_info\x18\x02 \x01(\bR\x0fincludeRepoInfo\"U\n" +
	"\x15GetCollectionResponse\x12<\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x1c.myawesomelist.v1.CollectionR\n" +
	"collection\"r\n" +
	"\x15ListCategoriesRequest\x12-\n" +
	"\x04repo\x18\x01 \x01(\v2\x19.myawesomelist.v1.RepoRefR\x04repo\x12*\n" +
	"\x11include_repo_info\x18\x02 \x01(\bR\x0fincludeRepoInfo\"T\n" +
	"\x16ListCategoriesResponse\x12:\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1a.myawesomelist.v1.CategoryR\n" +
	"categories\"\x95\x01\n" +
	"\x13ListProjectsRequest\x12-\n" +
	"\x04repo\x18\x01 \x01(\v2\x19.myawesomelist.v1.RepoRefR\x04repo\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12*\n" +
	"\x11include_repo_info\x18\x03 \x01(\bR\x0fincludeRepoInfo\"M\n" +
	"\x14ListProjectsResponse\x125\n" +
	"\bprojects\x18\x01 \x03(\v2\x19.myawesomelist.v1.ProjectR\bprojects\"\xa0\x01\n" +
	"\x15SearchProjectsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12/\n" +
	"\x05repos\x18\x03 \x03(\v2\x19.myawesomelist.v1.RepoRefR\x05repos\x12*\n" +
	"\x11include_repo_info\x18\x04 \x01(\bR\x0fincludeRepoInfo\"O\n" +
	"\x16SearchProjectsResponse\x125\n" +
	"\bprojects\x18\x01 \x03(\v2\x19.myawesomelist.v1.ProjectR\bprojects\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xdf\x04\n" +
	"\x0eAwesomeService\x12Z\n" +
	"\vHealthCheck\x12$.myawesomelist.v1.HealthCheckRequest\x1a%.myawesomelist.v1.HealthCheckResponse\x12f\n" +
	"\x0fListCollections\x12(.myawesomelist.v1.ListCollectionsRequest\x1a).myawesomelist.v1.ListCollectionsResponse\x12`\n" +
	"\rGetCollection\x12&.myawesomelist.v1.GetCollectionRequest\x1a'.myawesomelist.v1.GetCollectionResponse\x12c\n" +
	"\x0eListCategories\x12'.myawesomelist.v1.ListCategoriesRequest\x1a(.myawesomelist.v1.ListCategoriesResponse\x12]\n" +
	"\fListProjects\x12%.myawesomelist.v1.ListProjectsRequest\x1a&.myawesomelist.v1.ListProjectsResponse\x12c\n" +
	"\x0eSearchProjects\x12'.myawesomelist.v1.SearchProjectsRequest\x1a(.myawesomelist.v1.SearchProjectsResponseBLZJmyawesomelist.shikanime.studio/pkgs/proto/myawesomelist/v1;myawesomelistv1b\x06proto3"

var (
	file_myawesomelist_v1_myawesomelist_proto_rawDescOnce sync.Once
	file_myawesomelist_v1_myawesomelist_proto_rawDescData []byte
)

func file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP() []byte {
	file_myawesomelist_v1_myawesomelist_proto_rawDescOnce.Do(func() {
		file_myawesomelist_v1_myawesomelist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myawesomelist_v1_myawesomelist_proto_rawDesc), len(file_myawesomelist_v1_myawesomelist_proto_rawDesc)))
	})
	return file_myawesomelist_v1_myawesomelist_proto_rawDescData
}

var file_myawesomelist_v1_myawesomelist_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_myawesomelist_v1_myawesomelist_proto_goTypes = []any{
	(*Project)(nil),                 // 0: myawesomelist.v1.Project
	(*Category)(nil),                // 1: myawesomelist.v1.Category
	(*Collection)(nil),              // 2: myawesomelist.v1.Collection
	(*RepoRef)(nil),                 // 3: myawesomelist.v1.RepoRef
	(*ListCollectionsRequest)(nil),  // 4: myawesomelist.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil), // 5: myawesomelist.v1.ListCollectionsResponse
	(*GetCollectionRequest)(nil),    // 6: myawesomelist.v1.GetCollectionRequest
	(*GetCollectionResponse)(nil),   // 7: myawesomelist.v1.GetCollectionResponse
	(*ListCategoriesRequest)(nil),   // 8: myawesomelist.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),  // 9: myawesomelist.v1.ListCategoriesResponse
	(*ListProjectsRequest)(nil),     // 10: myawesomelist.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),    // 11: myawesomelist.v1.ListProjectsResponse
	(*SearchProjectsRequest)(nil),   // 12: myawesomelist.v1.SearchProjectsRequest
	(*SearchProjectsResponse)(nil),  // 13: myawesomelist.v1.SearchProjectsResponse
	(*HealthCheckRequest)(nil),      // 14: myawesomelist.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 15: myawesomelist.v1.HealthCheckResponse
}
var file_myawesomelist_v1_myawesomelist_proto_depIdxs = []int32{
	0,  // 0: myawesomelist.v1.Category.projects:type_name -> myawesomelist.v1.Project
	1,  // 1: myawesomelist.v1.Collection.categories:type_name -> myawesomelist.v1.Category
	3,  // 2: myawesomelist.v1.ListCollectionsRequest.repos:type_name -> myawesomelist.v1.RepoRef
	2,  // 3: myawesomelist.v1.ListCollectionsResponse.collections:type_name -> myawesomelist.v1.Collection
	3,  // 4: myawesomelist.v1.GetCollectionRequest.repo:type_name -> myawesomelist.v1.RepoRef
	2,  // 5: myawesomelist.v1.GetCollectionResponse.collection:type_name -> myawesomelist.v1.Collection
	3,  // 6: myawesomelist.v1.ListCategoriesRequest.repo:type_name -> myawesomelist.v1.RepoRef
	1,  // 7: myawesomelist.v1.ListCategoriesResponse.categories:type_name -> myawesomelist.v1.Category
	3,  // 8: myawesomelist.v1.ListProjectsRequest.repo:type_name -> myawesomelist.v1.RepoRef
	0,  // 9: myawesomelist.v1.ListProjectsResponse.projects:type_name -> myawesomelist.v1.Project
	3,  // 10: myawesomelist.v1.SearchProjectsRequest.repos:type_name -> myawesomelist.v1.RepoRef
	0,  // 11: myawesomelist.v1.SearchProjectsResponse.projects:type_name -> myawesomelist.v1.Project
	14, // 12: myawesomelist.v1.AwesomeService.HealthCheck:input_type -> myawesomelist.v1.HealthCheckRequest
	4,  // 13: myawesomelist.v1.AwesomeService.ListCollections:input_type -> myawesomelist.v1.ListCollectionsRequest
	6,  // 14: myawesomelist.v1.AwesomeService.GetCollection:input_type -> myawesomelist.v1.GetCollectionRequest
	8,  // 15: myawesomelist.v1.AwesomeService.ListCategories:input_type -> myawesomelist.v1.ListCategoriesRequest
	10, // 16: myawesomelist.v1.AwesomeService.ListProjects:input_type -> myawesomelist.v1.ListProjectsRequest
	12, // 17: myawesomelist.v1.AwesomeService.SearchProjects:input_type -> myawesomelist.v1.SearchProjectsRequest
	15, // 18: myawesomelist.v1.AwesomeService.HealthCheck:output_type -> myawesomelist.v1.HealthCheckResponse
	5,  // 19: myawesomelist.v1.AwesomeService.ListCollections:output_type -> myawesomelist.v1.ListCollectionsResponse
	7,  // 20: myawesomelist.v1.AwesomeService.GetCollection:output_type -> myawesomelist.v1.GetCollectionResponse
	9,  // 21: myawesomelist.v1.AwesomeService.ListCategories:output_type -> myawesomelist.v1.ListCategoriesResponse
	11, // 22: myawesomelist.v1.AwesomeService.ListProjects:output_type -> myawesomelist.v1.ListProjectsResponse
	13, // 23: myawesomelist.v1.AwesomeService.SearchProjects:output_type -> myawesomelist.v1.SearchProjectsResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_myawesomelist_v1_myawesomelist_proto_init() }
func file_myawesomelist_v1_myawesomelist_proto_init() {
	if File_myawesomelist_v1_myawesomelist_proto != nil {
		return
	}
	file_myawesomelist_v1_myawesomelist_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myawesomelist_v1_myawesomelist_proto_rawDesc), len(file_myawesomelist_v1_myawesomelist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myawesomelist_v1_myawesomelist_proto_goTypes,
		DependencyIndexes: file_myawesomelist_v1_myawesomelist_proto_depIdxs,
		MessageInfos:      file_myawesomelist_v1_myawesomelist_proto_msgTypes,
	}.Build()
	File_myawesomelist_v1_myawesomelist_proto = out.File
	file_myawesomelist_v1_myawesomelist_proto_goTypes = nil
	file_myawesomelist_v1_myawesomelist_proto_depIdxs = nil
}
