// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: myawesomelist/v1/myawesomelist.proto

package myawesomelistv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project represents a single project from an awesome list
type ProjectStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StargazersCount *uint32                `protobuf:"varint,2,opt,name=stargazers_count,json=stargazersCount,proto3,oneof" json:"stargazers_count,omitempty"`
	OpenIssueCount  *uint32                `protobuf:"varint,3,opt,name=open_issue_count,json=openIssueCount,proto3,oneof" json:"open_issue_count,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectStats) Reset() {
	*x = ProjectStats{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectStats) ProtoMessage() {}

func (x *ProjectStats) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectStats.ProtoReflect.Descriptor instead.
func (*ProjectStats) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectStats) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectStats) GetStargazersCount() uint32 {
	if x != nil && x.StargazersCount != nil {
		return *x.StargazersCount
	}
	return 0
}

func (x *ProjectStats) GetOpenIssueCount() uint32 {
	if x != nil && x.OpenIssueCount != nil {
		return *x.OpenIssueCount
	}
	return 0
}

func (x *ProjectStats) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Repo          *Repository            `protobuf:"bytes,4,opt,name=repo,proto3" json:"repo,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetRepo() *Repository {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Category groups projects under a section
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Projects      []*Project             `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{2}
}

func (x *Category) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *Category) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Collection represents an awesome repository parsed into categories
type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Repo          *Repository            `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Categories    []*Category            `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{3}
}

func (x *Collection) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Collection) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Collection) GetRepo() *Repository {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *Collection) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Collection) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Identify a source awesome repository (owner/repo)
type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{4}
}

func (x *Repository) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Repository) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Repository) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*Repository          `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{5}
}

func (x *ListCollectionsRequest) GetRepos() []*Repository {
	if x != nil {
		return x.Repos
	}
	return nil
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*Collection          `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{6}
}

func (x *ListCollectionsResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *Repository            `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{7}
}

func (x *GetCollectionRequest) GetRepo() *Repository {
	if x != nil {
		return x.Repo
	}
	return nil
}

type GetCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{8}
}

func (x *GetCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *Repository            `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{9}
}

func (x *ListCategoriesRequest) GetRepo() *Repository {
	if x != nil {
		return x.Repo
	}
	return nil
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{10}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *Repository            `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{11}
}

func (x *ListProjectsRequest) GetRepo() *Repository {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *ListProjectsRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{12}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type SearchProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Repos         []*Repository          `protobuf:"bytes,3,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProjectsRequest) Reset() {
	*x = SearchProjectsRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProjectsRequest) ProtoMessage() {}

func (x *SearchProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProjectsRequest.ProtoReflect.Descriptor instead.
func (*SearchProjectsRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{13}
}

func (x *SearchProjectsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProjectsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchProjectsRequest) GetRepos() []*Repository {
	if x != nil {
		return x.Repos
	}
	return nil
}

type SearchProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProjectsResponse) Reset() {
	*x = SearchProjectsResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProjectsResponse) ProtoMessage() {}

func (x *SearchProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProjectsResponse.ProtoReflect.Descriptor instead.
func (*SearchProjectsResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{14}
}

func (x *SearchProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type LivenessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessRequest) Reset() {
	*x = LivenessRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessRequest) ProtoMessage() {}

func (x *LivenessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessRequest.ProtoReflect.Descriptor instead.
func (*LivenessRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{15}
}

type LivenessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessResponse) Reset() {
	*x = LivenessResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessResponse) ProtoMessage() {}

func (x *LivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessResponse.ProtoReflect.Descriptor instead.
func (*LivenessResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{16}
}

type ReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessRequest) Reset() {
	*x = ReadinessRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessRequest) ProtoMessage() {}

func (x *ReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessRequest.ProtoReflect.Descriptor instead.
func (*ReadinessRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{17}
}

type ReadinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessResponse) Reset() {
	*x = ReadinessResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessResponse) ProtoMessage() {}

func (x *ReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessResponse.ProtoReflect.Descriptor instead.
func (*ReadinessResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{18}
}

type GetProjectStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *Repository            `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectStatsRequest) Reset() {
	*x = GetProjectStatsRequest{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectStatsRequest) ProtoMessage() {}

func (x *GetProjectStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectStatsRequest.ProtoReflect.Descriptor instead.
func (*GetProjectStatsRequest) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{19}
}

func (x *GetProjectStatsRequest) GetRepo() *Repository {
	if x != nil {
		return x.Repo
	}
	return nil
}

type GetProjectStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *ProjectStats          `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectStatsResponse) Reset() {
	*x = GetProjectStatsResponse{}
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectStatsResponse) ProtoMessage() {}

func (x *GetProjectStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myawesomelist_v1_myawesomelist_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectStatsResponse.ProtoReflect.Descriptor instead.
func (*GetProjectStatsResponse) Descriptor() ([]byte, []int) {
	return file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP(), []int{20}
}

func (x *GetProjectStatsResponse) GetStats() *ProjectStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_myawesomelist_v1_myawesomelist_proto protoreflect.FileDescriptor

const file_myawesomelist_v1_myawesomelist_proto_rawDesc = "" +
	"\n" +
	"$myawesomelist/v1/myawesomelist.proto\x12\x10myawesomelist.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\fProjectStats\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12.\n" +
	"\x10stargazers_count\x18\x02 \x01(\rH\x00R\x0fstargazersCount\x88\x01\x01\x12-\n" +
	"\x10open_issue_count\x18\x03 \x01(\rH\x01R\x0eopenIssueCount\x88\x01\x01\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x13\n" +
	"\x11_stargazers_countB\x13\n" +
	"\x11_open_issue_count\"\xbc\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x04repo\x18\x04 \x01(\v2\x1c.myawesomelist.v1.RepositoryR\x04repo\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa0\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\bprojects\x18\x03 \x03(\v2\x19.myawesomelist.v1.ProjectR\bprojects\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe1\x01\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x120\n" +
	"\x04repo\x18\x03 \x01(\v2\x1c.myawesomelist.v1.RepositoryR\x04repo\x12:\n" +
	"\n" +
	"categories\x18\x04 \x03(\v2\x1a.myawesomelist.v1.CategoryR\n" +
	"categories\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"R\n" +
	"\n" +
	"Repository\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\"L\n" +
	"\x16ListCollectionsRequest\x122\n" +
	"\x05repos\x18\x01 \x03(\v2\x1c.myawesomelist.v1.RepositoryR\x05repos\"Y\n" +
	"\x17ListCollectionsResponse\x12>\n" +
	"\vcollections\x18\x01 \x03(\v2\x1c.myawesomelist.v1.CollectionR\vcollections\"H\n" +
	"\x14GetCollectionRequest\x120\n" +
	"\x04repo\x18\x01 \x01(\v2\x1c.myawesomelist.v1.RepositoryR\x04repo\"U\n" +
	"\x15GetCollectionResponse\x12<\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x1c.myawesomelist.v1.CollectionR\n" +
	"collection\"I\n" +
	"\x15ListCategoriesRequest\x120\n" +
	"\x04repo\x18\x01 \x01(\v2\x1c.myawesomelist.v1.RepositoryR\x04repo\"T\n" +
	"\x16ListCategoriesResponse\x12:\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1a.myawesomelist.v1.CategoryR\n" +
	"categories\"l\n" +
	"\x13ListProjectsRequest\x120\n" +
	"\x04repo\x18\x01 \x01(\v2\x1c.myawesomelist.v1.RepositoryR\x04repo\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\"M\n" +
	"\x14ListProjectsResponse\x125\n" +
	"\bprojects\x18\x01 \x03(\v2\x19.myawesomelist.v1.ProjectR\bprojects\"w\n" +
	"\x15SearchProjectsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x122\n" +
	"\x05repos\x18\x03 \x03(\v2\x1c.myawesomelist.v1.RepositoryR\x05repos\"O\n" +
	"\x16SearchProjectsResponse\x125\n" +
	"\bprojects\x18\x01 \x03(\v2\x19.myawesomelist.v1.ProjectR\bprojects\"\x11\n" +
	"\x0fLivenessRequest\"\x12\n" +
	"\x10LivenessResponse\"\x12\n" +
	"\x10ReadinessRequest\"\x13\n" +
	"\x11ReadinessResponse\"J\n" +
	"\x16GetProjectStatsRequest\x120\n" +
	"\x04repo\x18\x01 \x01(\v2\x1c.myawesomelist.v1.RepositoryR\x04repo\"O\n" +
	"\x17GetProjectStatsResponse\x124\n" +
	"\x05stats\x18\x01 \x01(\v2\x1e.myawesomelist.v1.ProjectStatsR\x05stats2\x94\x06\n" +
	"\x0eAwesomeService\x12Q\n" +
	"\bLiveness\x12!.myawesomelist.v1.LivenessRequest\x1a\".myawesomelist.v1.LivenessResponse\x12T\n" +
	"\tReadiness\x12\".myawesomelist.v1.ReadinessRequest\x1a#.myawesomelist.v1.ReadinessResponse\x12f\n" +
	"\x0fListCollections\x12(.myawesomelist.v1.ListCollectionsRequest\x1a).myawesomelist.v1.ListCollectionsResponse\x12`\n" +
	"\rGetCollection\x12&.myawesomelist.v1.GetCollectionRequest\x1a'.myawesomelist.v1.GetCollectionResponse\x12c\n" +
	"\x0eListCategories\x12'.myawesomelist.v1.ListCategoriesRequest\x1a(.myawesomelist.v1.ListCategoriesResponse\x12]\n" +
	"\fListProjects\x12%.myawesomelist.v1.ListProjectsRequest\x1a&.myawesomelist.v1.ListProjectsResponse\x12c\n" +
	"\x0eSearchProjects\x12'.myawesomelist.v1.SearchProjectsRequest\x1a(.myawesomelist.v1.SearchProjectsResponse\x12f\n" +
	"\x0fGetProjectStats\x12(.myawesomelist.v1.GetProjectStatsRequest\x1a).myawesomelist.v1.GetProjectStatsResponseBLZJmyawesomelist.shikanime.studio/pkgs/proto/myawesomelist/v1;myawesomelistv1b\x06proto3"

var (
	file_myawesomelist_v1_myawesomelist_proto_rawDescOnce sync.Once
	file_myawesomelist_v1_myawesomelist_proto_rawDescData []byte
)

func file_myawesomelist_v1_myawesomelist_proto_rawDescGZIP() []byte {
	file_myawesomelist_v1_myawesomelist_proto_rawDescOnce.Do(func() {
		file_myawesomelist_v1_myawesomelist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myawesomelist_v1_myawesomelist_proto_rawDesc), len(file_myawesomelist_v1_myawesomelist_proto_rawDesc)))
	})
	return file_myawesomelist_v1_myawesomelist_proto_rawDescData
}

var file_myawesomelist_v1_myawesomelist_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_myawesomelist_v1_myawesomelist_proto_goTypes = []any{
	(*ProjectStats)(nil),            // 0: myawesomelist.v1.ProjectStats
	(*Project)(nil),                 // 1: myawesomelist.v1.Project
	(*Category)(nil),                // 2: myawesomelist.v1.Category
	(*Collection)(nil),              // 3: myawesomelist.v1.Collection
	(*Repository)(nil),              // 4: myawesomelist.v1.Repository
	(*ListCollectionsRequest)(nil),  // 5: myawesomelist.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil), // 6: myawesomelist.v1.ListCollectionsResponse
	(*GetCollectionRequest)(nil),    // 7: myawesomelist.v1.GetCollectionRequest
	(*GetCollectionResponse)(nil),   // 8: myawesomelist.v1.GetCollectionResponse
	(*ListCategoriesRequest)(nil),   // 9: myawesomelist.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),  // 10: myawesomelist.v1.ListCategoriesResponse
	(*ListProjectsRequest)(nil),     // 11: myawesomelist.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),    // 12: myawesomelist.v1.ListProjectsResponse
	(*SearchProjectsRequest)(nil),   // 13: myawesomelist.v1.SearchProjectsRequest
	(*SearchProjectsResponse)(nil),  // 14: myawesomelist.v1.SearchProjectsResponse
	(*LivenessRequest)(nil),         // 15: myawesomelist.v1.LivenessRequest
	(*LivenessResponse)(nil),        // 16: myawesomelist.v1.LivenessResponse
	(*ReadinessRequest)(nil),        // 17: myawesomelist.v1.ReadinessRequest
	(*ReadinessResponse)(nil),       // 18: myawesomelist.v1.ReadinessResponse
	(*GetProjectStatsRequest)(nil),  // 19: myawesomelist.v1.GetProjectStatsRequest
	(*GetProjectStatsResponse)(nil), // 20: myawesomelist.v1.GetProjectStatsResponse
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
}
var file_myawesomelist_v1_myawesomelist_proto_depIdxs = []int32{
	21, // 0: myawesomelist.v1.ProjectStats.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 1: myawesomelist.v1.Project.repo:type_name -> myawesomelist.v1.Repository
	21, // 2: myawesomelist.v1.Project.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: myawesomelist.v1.Category.projects:type_name -> myawesomelist.v1.Project
	21, // 4: myawesomelist.v1.Category.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 5: myawesomelist.v1.Collection.repo:type_name -> myawesomelist.v1.Repository
	2,  // 6: myawesomelist.v1.Collection.categories:type_name -> myawesomelist.v1.Category
	21, // 7: myawesomelist.v1.Collection.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 8: myawesomelist.v1.ListCollectionsRequest.repos:type_name -> myawesomelist.v1.Repository
	3,  // 9: myawesomelist.v1.ListCollectionsResponse.collections:type_name -> myawesomelist.v1.Collection
	4,  // 10: myawesomelist.v1.GetCollectionRequest.repo:type_name -> myawesomelist.v1.Repository
	3,  // 11: myawesomelist.v1.GetCollectionResponse.collection:type_name -> myawesomelist.v1.Collection
	4,  // 12: myawesomelist.v1.ListCategoriesRequest.repo:type_name -> myawesomelist.v1.Repository
	2,  // 13: myawesomelist.v1.ListCategoriesResponse.categories:type_name -> myawesomelist.v1.Category
	4,  // 14: myawesomelist.v1.ListProjectsRequest.repo:type_name -> myawesomelist.v1.Repository
	1,  // 15: myawesomelist.v1.ListProjectsResponse.projects:type_name -> myawesomelist.v1.Project
	4,  // 16: myawesomelist.v1.SearchProjectsRequest.repos:type_name -> myawesomelist.v1.Repository
	1,  // 17: myawesomelist.v1.SearchProjectsResponse.projects:type_name -> myawesomelist.v1.Project
	4,  // 18: myawesomelist.v1.GetProjectStatsRequest.repo:type_name -> myawesomelist.v1.Repository
	0,  // 19: myawesomelist.v1.GetProjectStatsResponse.stats:type_name -> myawesomelist.v1.ProjectStats
	15, // 20: myawesomelist.v1.AwesomeService.Liveness:input_type -> myawesomelist.v1.LivenessRequest
	17, // 21: myawesomelist.v1.AwesomeService.Readiness:input_type -> myawesomelist.v1.ReadinessRequest
	5,  // 22: myawesomelist.v1.AwesomeService.ListCollections:input_type -> myawesomelist.v1.ListCollectionsRequest
	7,  // 23: myawesomelist.v1.AwesomeService.GetCollection:input_type -> myawesomelist.v1.GetCollectionRequest
	9,  // 24: myawesomelist.v1.AwesomeService.ListCategories:input_type -> myawesomelist.v1.ListCategoriesRequest
	11, // 25: myawesomelist.v1.AwesomeService.ListProjects:input_type -> myawesomelist.v1.ListProjectsRequest
	13, // 26: myawesomelist.v1.AwesomeService.SearchProjects:input_type -> myawesomelist.v1.SearchProjectsRequest
	19, // 27: myawesomelist.v1.AwesomeService.GetProjectStats:input_type -> myawesomelist.v1.GetProjectStatsRequest
	16, // 28: myawesomelist.v1.AwesomeService.Liveness:output_type -> myawesomelist.v1.LivenessResponse
	18, // 29: myawesomelist.v1.AwesomeService.Readiness:output_type -> myawesomelist.v1.ReadinessResponse
	6,  // 30: myawesomelist.v1.AwesomeService.ListCollections:output_type -> myawesomelist.v1.ListCollectionsResponse
	8,  // 31: myawesomelist.v1.AwesomeService.GetCollection:output_type -> myawesomelist.v1.GetCollectionResponse
	10, // 32: myawesomelist.v1.AwesomeService.ListCategories:output_type -> myawesomelist.v1.ListCategoriesResponse
	12, // 33: myawesomelist.v1.AwesomeService.ListProjects:output_type -> myawesomelist.v1.ListProjectsResponse
	14, // 34: myawesomelist.v1.AwesomeService.SearchProjects:output_type -> myawesomelist.v1.SearchProjectsResponse
	20, // 35: myawesomelist.v1.AwesomeService.GetProjectStats:output_type -> myawesomelist.v1.GetProjectStatsResponse
	28, // [28:36] is the sub-list for method output_type
	20, // [20:28] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_myawesomelist_v1_myawesomelist_proto_init() }
func file_myawesomelist_v1_myawesomelist_proto_init() {
	if File_myawesomelist_v1_myawesomelist_proto != nil {
		return
	}
	file_myawesomelist_v1_myawesomelist_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myawesomelist_v1_myawesomelist_proto_rawDesc), len(file_myawesomelist_v1_myawesomelist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myawesomelist_v1_myawesomelist_proto_goTypes,
		DependencyIndexes: file_myawesomelist_v1_myawesomelist_proto_depIdxs,
		MessageInfos:      file_myawesomelist_v1_myawesomelist_proto_msgTypes,
	}.Build()
	File_myawesomelist_v1_myawesomelist_proto = out.File
	file_myawesomelist_v1_myawesomelist_proto_goTypes = nil
	file_myawesomelist_v1_myawesomelist_proto_depIdxs = nil
}
